sudo: true
dist: trusty
language: python
python:
  - "3.5"
services:
  - docker

jobs:
  include:
    - stage: Building preCICE
      name: "Ubuntu 18.04.home"
      if: fork = false
      script:
        - docker build -f precice/Dockerfile.Ubuntu1804.home -t benjaminrueth/precice-ubuntu1804.home-develop .
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo "$DOCKER_PASSWORD" | docker login -u precice --password-stdin &&
          docker push benjaminrueth/precice-ubuntu1804.home-develop:latest

    - stage: Building Adapters
      name: FEniCS adapter
      if: fork = false
      script:
        - >
          docker build -f adapters/Dockerfile.fenics-adapter -t benjaminrueth/fenics-adapter-ubuntu1804.home-develop
          --build-arg from=benjaminrueth/precice-ubuntu1804.home-develop .
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
          docker push benjaminrueth/fenics-adapter-ubuntu1804.home-develop

    - stage: Running tests
      name: "[18.04] FEniCS <-> FEniCS"
      script:
        - python system_testing.py -s fe-fe --base Ubuntu1804.home
      after_failure:
        - python push.py -t fe-fe --base Ubuntu1804.home
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: python push.py -s -t fe-fe --base Ubuntu1804.home
