sudo: true
dist: trusty
language: python
python:
  - "3.5"
services:
  - docker

jobs:
  allow_failures:
    - name: "Ubuntu 18.04.sudo.mpich [Job failure permitted]"
    - name: "Ubuntu 16.04 home PETSc [Job failure permitted]"
    - name: "[16.04 PETSc] OpenFOAM <-> CalculiX [FSI] [Job failure permitted]"
    - name: "openFOAM adapter [PETSc] [Job failure permitted]"
    - name: "CalculiX adapter [PETSc] [Job failure permitted]"

  include:
    - stage: Building preCICE
      name: "Arch Linux"
      script:
        - python build_precice.py --dockerfile precice/Dockerfile.Arch --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_precice.py --dockerfile precice/Dockerfile.Arch --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - stage: Building preCICE
      name: "Ubuntu 16.04 home"
      script:
        - python build_precice.py --dockerfile precice/Dockerfile.Ubuntu1604.home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_precice.py --dockerfile precice/Dockerfile.Ubuntu1604.home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - stage: Building preCICE
      name: "Ubuntu 16.04 home PETSc [Job failure permitted]"
      script:
        - python build_precice.py --dockerfile precice/Dockerfile.Ubuntu1604.home --petsc yes --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_precice.py --dockerfile precice/Dockerfile.Ubuntu1604.home --petsc yes --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - stage: Building preCICE
      name: "Ubuntu 16.04.sudo"
      script:
        - python build_precice.py --dockerfile precice/Dockerfile.Ubuntu1604.sudo --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_precice.py --dockerfile precice/Dockerfile.Ubuntu1604.sudo --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - stage: Building preCICE
      name: "Ubuntu 18.04.home"
      script:
        - python build_precice.py --dockerfile precice/Dockerfile.Ubuntu1804.home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_precice.py --dockerfile precice/Dockerfile.Ubuntu1804.home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - stage: Building preCICE
      name: "Ubuntu 18.04.sudo"
      script:
        - python build_precice.py --dockerfile precice/Dockerfile.Ubuntu1804.sudo --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_precice.py --dockerfile precice/Dockerfile.Ubuntu1804.sudo --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - stage: Building preCICE
      name: "Ubuntu 18.04.sudo.mpich [Job failure permitted]"
      script:
        - python build_precice.py --dockerfile precice/Dockerfile.Ubuntu1804.sudo.mpich --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_precice.py --dockerfile precice/Dockerfile.Ubuntu1804.sudo.mpich --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - stage: Building preCICE
      name: "Ubuntu 18.04.package"
      script:
        - python build_precice.py --dockerfile precice/Dockerfile.Ubuntu1804.package --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_precice.py --dockerfile precice/Dockerfile.Ubuntu1804.package --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - stage: Building adapters
      name: SU2 adapter
      script:
        - python build_adapter.py --dockerfile adapters/Dockerfile.su2-adapter --operating-system ubuntu1604 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_adapter.py --dockerfile adapters/Dockerfile.su2-adapter --operating-system ubuntu1604 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - name: CalculiX adapter
      script:
        - python build_adapter.py --dockerfile adapters/Dockerfile.calculix-adapter --operating-system ubuntu1604 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_adapter.py --dockerfile adapters/Dockerfile.calculix-adapter --operating-system ubuntu1604 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - name: deal.ii adapter
      script:
        - python build_adapter.py --dockerfile adapters/Dockerfile.dealii-adapter --operating-system ubuntu1604 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_adapter.py --dockerfile adapters/Dockerfile.dealii-adapter --operating-system ubuntu1604 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - name: "[16.04] openFOAM adapter"
      script:
        - python build_adapter.py --dockerfile adapters/Dockerfile.openfoam-adapter --operating-system ubuntu1604 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_adapter.py --dockerfile adapters/Dockerfile.openfoam-adapter --operating-system ubuntu1604 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - name: "[18.04] openFOAM adapter"
      script:
        - python build_adapter.py --dockerfile adapters/Dockerfile.openfoam-adapter --operating-system ubuntu1804 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_adapter.py --dockerfile adapters/Dockerfile.openfoam-adapter --operating-system ubuntu1804 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - name: FEniCS adapter
      script:
        - python build_adapter.py --dockerfile adapters/Dockerfile.fenics-adapter --operating-system ubuntu1804 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_adapter.py --dockerfile adapters/Dockerfile.fenics-adapter --operating-system ubuntu1804 --precice-installation home --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - name: openFOAM adapter [PETSc] [Job failure permitted]
      script:
        - python build_adapter.py --dockerfile adapters/Dockerfile.openfoam-adapter --operating-system ubuntu1604 --precice-installation home --petsc yes --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_adapter.py --dockerfile adapters/Dockerfile.openfoam-adapter --operating-system ubuntu1604 --precice-installation home --petsc yes --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - name: CalculiX adapter [PETSc] [Job failure permitted]
      script:
        - python build_adapter.py --dockerfile adapters/Dockerfile.calculix-adapter --operating-system ubuntu1604 --precice-installation home --petsc yes --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH
      deploy:
        skip_cleanup: true
        provider: script
        on:
          all_branches: true
        script: >-
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
          python push_adapter.py --dockerfile adapters/Dockerfile.calculix-adapter --operating-system ubuntu1604 --precice-installation home --petsc yes --docker-username $DOCKER_USERNAME --branch $TRAVIS_BRANCH

    - stage: Tests
      name: "[16.04] SU2 <-> Calculix"
      script:
        - python system_testing.py -s su2-ccx --branch $TRAVIS_BRANCH
        - python push.py -t su2-ccx

    - name: "[16.04] OpenFOAM <-> OpenFOAM"
      script:
        - python system_testing.py -s of-of --branch $TRAVIS_BRANCH
        - python push.py -t of-of

    - name: "[16.04] Calculix <-> OpenFOAM"
      script:
        - python system_testing.py -s of-ccx --branch $TRAVIS_BRANCH
        - python push.py -t of-ccx

    - name: "[18.04] FEniCS <-> FEniCS"
      script:
        - python system_testing.py -s fe-fe --base Ubuntu1804.home --branch $TRAVIS_BRANCH
        - python push.py -t fe-fe --base Ubuntu1804.home

    - name: "[16.04] Bindings/Solverdummies"
      script:
        - python system_testing.py -s bindings --branch $TRAVIS_BRANCH
        - python push.py -t bindings

    - name: "[16.04] deal.ii <-> OpenFOAM"
      script:
        - python system_testing.py -s dealii-of --branch $TRAVIS_BRANCH
        - python push.py -t dealii-of

    - name: "[18.04] nutils <-> OpenFOAM"
      script:
        - python system_testing.py -s nutils-of --base Ubuntu1804.home --branch $TRAVIS_BRANCH
        - python push.py -t nutils-of --base Ubuntu1804.home

    - name: "[16.04] OpenFOAM <-> OpenFOAM [nearest projection]"
      script:
        - python system_testing.py -s of-of_np --branch $TRAVIS_BRANCH
        - python push.py -t of-of_np

    - name: "[16.04 PETSc] OpenFOAM <-> CalculiX [FSI] [Job failure permitted]"
      script:
        - python system_testing.py -s of-ccx_fsi --base Ubuntu1604.home.PETSc --branch $TRAVIS_BRANCH
        - python push.py -t of-ccx_fsi --petsc
