sudo: true
dist: trusty
notifications:
  email:
    recipients:
    - kunstrasenspringer@gmx.net
    - kunstrasenspringer@googlemail.com
    on_success: never
    on_failure: always
jobs:
  include:
  - stage: Building preCICE
    script:
    - docker build -f Dockerfile.precice -t precice .
    after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker images
    - docker tag precice $DOCKER_USERNAME/precice
    - docker push $DOCKER_USERNAME/precice
  - stage: System Tests
    script:
    - python system_testing.py su2-ccx
    after_success:
    - python push.py 1 su2-ccx
    after_failure:
    - python push.py 0 su2-ccx
  - script:
    - python system_testing.py of-of
    after_success:
    - python push.py 1 of-of
    after_failure:
    - python push.py 0 of-of
  - script:
    - python system_testing.py of-ccx
    after_success:
    - python push.py 1 of-ccx
    after_failure:
    - python push.py 0 of-ccx
env:
  global:
    secure: UwGv0skdfJ5Tc6n+iVI645d2m+M57/1n135sTHtR634U/BtlaU8qi9WE0zo8qcg58hJI4CdKBdTPLIQGUhPzy6ELdu1EyYFgvSg/+eT4tVjd1Eo/hmi6NRSUeWfRTrnvNEm5OP+rAxbpbHvSMCp6OZxLhUMR3APxhImXEf7AU0a99yq8gprahYlr24f28e5JFyFQWX1A1vK2sYRTbsr0zroYFSR07u2idyFptL5hbnEb41fqS2jMUZFyWC02SYQBFItN3s20UlZLT+WMCjn/L5ksi1Jqlc51NkLykhy0k5JRFOaYl+40l4giKrXOfVe7dKXux74O/wIqWE8Voo7Q4kmPrf8DBzz3K6E+AR8LdsxhbOy6QRW2t6OnI44T+8XtnQThUxzV+wsjdC3n5AMkpifdfBTiMrRfQVNV5KIOYAVXC7HnAPhvF6rGiyqAdY/2YPgwSlHR9WUgFydlEzsCjJw+PcJYGg00YlK8/RExa/U6kjnRqvKtYsGkctwunEANQ52PUKnvEaC+HX3h/KqJlesFKbKnKjNbXOjOF8oAOfZHNBP5v81s9UBM/yuZFrn7O0+eoTooPobIZ2/TqoW5l4sUAS2QR16aIGyjCPoO24VMjcNlVIz2Uq7IF0kNwi4KQuOeWhe2DbkGCOLLcm5sUhtGd3QMig6UMMQKTiD2ZtY=
