from alpine
ENV tutorial_path tutorials/FSI/flap_perp/SU2-CalculiX
RUN apk add git bash
ARG branch=develop
RUN git clone https://github.com/precice/tutorials && cd tutorials && git checkout 2422f5760fa75e793c7bd9d897e33273d21faaec && cd ..
RUN git log -1

RUN mkdir configs && sed -e 's|exchange-directory="../"|exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g'\
    $tutorial_path/precice-config.xml  > configs/precice-config.xml
RUN rm $tutorial_path/precice-config.xml
RUN cp $tutorial_path/config.yml configs/
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
